services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: data
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  db-data: